---

language: python
python: "2.7"

branches:
  only:
    - develop
    - master

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==1.9.4

script:
  # Install Role Dependencies
  - make test_deps
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check --list-tasks -i tests/vagrant/inventory tests/vagrant/test.yml
  # First run
  - cd tests/vagrant/
  # Test the "build" stage
  - ansible-playbook -i inventory test.yml --tags=build --connection=local
  - >
    ansible-playbook -i inventory test.yml --tags=build --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
